sudo: required
language: generic
services:
  - docker

#before_install:
#  - docker build -t docker-angular -f ./client/Dockerfile.dev ./client

#script:
#  - docker run docker-angular npm run test-headless

after_success:
  - docker build -t vrady/multi-client ./client
  - docker build -t vrady/multi-nginx ./nginx
  - docker build -t vrady/multi-server ./server
  - docker build -t vrady/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vrady/multi-client
  - docker push vrady/multi-nginx
  - docker push vrady/multi-server
  - docker push vrady/multi-worker
